# Generated by Django 2.2 on 2024-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
