# Generated by Django 4.2.11 on 2024-03-20 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("techtreasure", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
