# Generated by Django 2.2.28 on 2024-03-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_field', models.ImageField(upload_to='')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemsold', models.BooleanField()),
                ('creation_date', models.DateTimeField()),
                ('description_field', models.CharField(max_length=500)),
                ('num_of_views', models.IntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offer_date', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techtreasure.Listing')),
            ],
        ),
        migrations.RemoveField(
            model_name='offers',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.AddField(
            model_name='offer',
            name='users',
            field=models.ManyToManyField(to='techtreasure.User'),
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techtreasure.Category'),
        ),
    ]
