# Generated by Django 2.2.28 on 2024-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0002_auto_20240306_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='num_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
