# Generated by Django 4.2.11 on 2024-03-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0002_remove_listing_user_listing_users_alter_offer_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture_field',
            field=models.ImageField(upload_to='listings'),
        ),
    ]
