# Generated by Django 2.2.28 on 2024-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0004_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
