# Generated by Django 2.2.28 on 2024-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techtreasure', '0002_delete_userprofile'),
        ('techtreasure', '0005_alter_listing_picture_field'),
    ]

    operations = [
    ]
